use_frameworks!

platform :ios, '8.0'

target 'TuyaSmartActivator_Example' do
  pod 'TuyaSmartMiniActivator', :git => 'https://github.com/TuyaInc/tuyasmart_ios_activator_sdk', :branch => 'develop_unicom'

  target 'TuyaSmartActivator_Tests' do
    inherit! :search_paths


  end
end
